### ISSUE TITLE
Potential polymorphism improvement

### ISSUE THREAD

**Issue by TesseractWorkshop** [VestOfHolding/SuperMarioPartyDice#1]
https://github.com/VestOfHolding/SuperMarioPartyDice/blob/7948d1488c6245a211824df27affd0ae22431647/src/main/java/boards/BaseBoard.java#L96

Why not just define `handleEventSpace` as a no-op in the base class, provide unique logic in the derived classes, and call the method regardless?  Less casting, and opens up usage to multiple implementations of an "event space".

**Comment by TesseractWorkshop** [comment]
Also, this seemed like a good excuse to associate my user account with this repo 🤷

**Comment by VestOfHolding** [comment]
Fixed! In retrospect there was literally zero point to me doing that, lol.
